backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "generalinformation"
    label: "General Information"
    files:
      - label: "Fonctionnalites"
        name: "fonctionnalites"
        file: "content/fonctionnalites.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Fonctionnalites"
            name: "fonctionnalites"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

      - label: "Pour quoi live tracking plus"
        name: "pourquoi"
        file: "content/pourquoi.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Pour quoi live tracking plus"
            name: "pourquoi"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

  - name: "happycustomers"
    label: "Happy Customers"
    files:
      - label: "Happy Customers"
        name: "happycustomers"
        file: "content/happycustomers.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Happy Customers"
            name: "happycustomers"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Featured Image", name: "thumbnail", widget: "image" }
              - { label: "City", name: "ciry", widget: "string" }
              - { label: "Country", name: "country", widget: "string" }
              - {
                  label: Rating,
                  name: "rating",
                  widget: "number",
                  default: 4,
                  value_type: "float",
                  min: 1,
                  max: 5,
                  step: 0.5,
                }
              - { label: "Testimoni", name: "testimoni", widget: "text" }
