backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "events"
    label: "Events"
    files:
      - label: "Events"
        name: "events"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Events"
            name: "events"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Featured Image", name: "thumbnail", widget: "image" }
              - { label: "Publish Date", name: "date", widget: "datetime" }
